"""Few-shot style examples — permanent, hidden from the user.
Used ONLY as internal style reference for the LLM when generating:
- Nota MedSys de Hospitalización (piso)
- Nota MedSys de UTI/UTIM
- Mensajes de WhatsApp para el médico tratante

These are the "gold standard" of the surgical residency service.
They must NEVER be shown to the user, never be copied verbatim, and never
be treated as clinical data. The LLM must learn ONLY: structure, order,
tone, vocabulary, length and the way information is integrated.
"""

HOSPITALIZATION_NOTE_EXAMPLES: list[str] = [
    """NOTA DE EVOLUCIÓN POR CIRUGÍA GENERAL / COLON Y RECTO

SE TRATA DE PACIENTE MASCULINO DE 70 AÑOS, MANUEL VELDERRAIN SANCHEZ ALDANA, QUIEN CUENTA CON LOS SIGUIENTES DIAGNÓSTICOS:
1. CHOQUE SÉPTICO SECUNDARIO A PERFORACIÓN DUODENAL + PO LAPE + PILOROPLASTIA + DRENAJE DE ABSCESO + LAVADO DE CAVIDAD
2. ADENOMA PARATIROIDEO PO 05/06/2026 EXPLORACIÓN CERVICAL + PARATIROIDECTOMÍA SUPERIOR IZQUIERDA CON NEUROMONITORIZACIÓN.
3. HIPERPARATIROIDISMO POR DOBLE ADENOMA ECTÓPICO PO 23/06/26 PARATIROIDECTOMÍA SUPERIOR DERECHA ECTÓPICA + EXPLORACIÓN CERVICAL DERECHA CON HALLAZGOS DE PARATIROIDES 1.4 GR COMPATIBLE CON ADENOMA EN ESTUDIO TRANSOPERATORIO. PARATIROIDES INFERIOR IZQUIERDA DE APARIENCIA NORMAL, ABUNDANTE TEJIDO DE INFLAMACIÓN EN LINEA MEDIA Y HEMICUELLO IZQUIERDO, PARATIROIDES SUPERIOR DERECHA RETROTRAQUEAL ECTÓPICA

AL PASE DE VISITA SE ENCUENTRA CON SIGNOS VITALES CON TENDENCIA A LA HIPERTENSION, MAXIMA DE 154/86 MMHG, EL DIA DE AYER CON MAL CONTROL ANALGESICO, ASOCIADO A DISTENSION ABDOMINAL CON REQUERIMIENTO DE RESCATES DE PARACETAMOL, BUTILHIOSCINA, TRIMEBUTINA, PARECOXIB. SE MANTIENE EN AYUNO, SONDA DE ALIMENTACION PERMEABLE. DIURESIS POR MICCIÓN ESPONTÁNEA PRESENTE, CANALIZA GASES, EVACUACIONES ESCASAS. CUENTA CON DRENAJE BLAKE DERECHO CON GASTO TURBIO REPORTADO EN 22 CC Y DRENAJE IZQUIERDO CON GASTO PURULENTO VERDOSO REPORTADO CON 10 CC. SE MANTIENE AFEBRIL EN MANEJO CON CEFTAZIDIMA / AVIBACTAM + AZTREONAM.

A LA EXPLORACIÓN FÍSICA PACIENTE ALERTA, REACTIVO Y COOPERADOR. CUELLO CILÍNDRICO SIMÉTRICO, CARDIORRESPIRATORIO SIN COMPROMISO. ABDOMEN GLOBOSO DISTENDIDO, TIMPANICO, BLANDO, DEPRESIBLE, NO DOLOROSO A LA PALPACIÓN GENERALIZADA, SIN DATOS DE IRRITACIÓN PERITONEAL, PERISTALSIS DISMINUIDA EN INTENSIDAD Y FRECUENCIA. DRENAJES PREVIAMENTE DESCRITOS. EXTREMIDADES ÍNTEGRAS.

PLAN. NUTRICION ENTERAL, ANTIBIOTICOTERAPIA, VIGILANCIA DE DRENAJES. COMPLETAR DIAS DE ANTIBIÓTICOS, PENDIENTE EVOLUCIÓN PARA POSTERIOR REINICIO DE LA VÍA ORAL.

PRONÓSTICO RESERVADO A EVOLUCIÓN
""",
    """NOTA DE EVOLUCIÓN POR CIRUGÍA GENERAL

SE TRATA DE MASCULINO DE 76 AÑOS, MANUEL RODRIGUEZ CAMPOMANES, CON DIAGNOSTICO DE TUMOR DE ILEON TERMINAL CON OCLUSIÓN CRONICA E ISQUEMIA DE ILEON POR LO QUE EL 26/12/2025 SE LE REALIZA LAPAROTOMÍA EXPLORADORA + RESECCION SEGMENTARIA DE ILEON CON ANASTOMOSIS LATERO LATERAL CON ENGRAPADORA DE ILEON CON HALLAZGOS DE OCLUSION CRONICA INTESTINAL DE ILEON DISTAL + TUMOR NEUROENDOCRINO DE ILEON

AL PASE DE VISITA SE ENCUENTRA CON SIGNOS VITALES ESTABLES, DENTRO DE PARÁMETROS NORMALES, SE MANTIENE EN AYUNO + NPT, SIN NÁUSEAS O VÓMITOS. CON DIURESIS POR MICCIÓN ESPONTÁNEA PRESENTE. PRESENTA 2 EVACUACIONES DE CARACTERÍSTICAS PASTOSAS ESCASAS Y CANALIZACIÓN DE GASES. SE MANTIENE CON BUEN CONTROL ANALGESICO. CUENTA CON DRENAJE BLAKE A HUECO PÉLVICO AL MOMENTO EN 204 CC SEROSOS. EN MANEJO CON MEROPENEM, VANCOMICINA Y ANIDULAFUNGINA, SIN FIEBRE O DATOS DE BACTERIEMIA. ACTUALMENTE EN PLAN EXPECTANTE, SIN PLAN QUIRÚRGICO HASTA EL MOMENTO. CONTINÚA CON EPISODIOS DE DELIRIUM HIPERACTIVO Y MAYOR CONFUSIÓN DE PREDOMINIO NOCTURNO, EN MANEJO CON QUETIAPINA. SE INTERCONSULTO A CLINICA DE HERIDAS POR ÚLCERA EN REGIÓN SACRA.

A LA EXPLORACIÓN FÍSICA ALERTA, REACTIVO, COOPERADOR. CABEZA Y CUELLO SIN ALTERACIONES. CARDIORRESPIRATORIO SIN COMPROMISO. ABDOMEN BLANDO, DEPRESIBLE, POCO DOLOROSO A LA PALPACION MEDIA Y PROFUNDA EN SITIO DE HERIDA QUIRURGICA, PERISTALSIS PRESENTE, HERIDA QUIRÚRGICA CUBIERTA, SIN DATOS DE SANGRADO ACTIVO, EDEMA, O ERITEMA PERILESIONAL. DRENAJE BLAKE DE CARACTERISTICAS PREVIAMENTE MENCIONADAS, EXTREMIDADES ÍNTEGRAS.

PLAN: AYUNO + NPT, SOLUCIONES Y ANALGESIA IV, CUIDADOS DE HERIDA QUIRÚRGICA, ANTIBIOTICOTERPIA IV, OXÍGENO SUPLEMENTARIO A 3 LPM, CUANTIFICACION DE DRENAJE BLAKE. TOMA DE LABORATORIOS EN AM. VIGILANCIA DE DATOS DE ABDOMEN AGUDO. SE PLANEA NUEVA TOMA DE TOMOGRAFÍA DE CONTROL EN BREVE.

PRONÓSTICO RESERVADO A EVOLUCIÓN
""",
    """NOTA DE EVOLUCIÓN POR CIRUGÍA GENERAL

SE TRATA DE PACIENTE MASCULINO DE 21 AÑOS, JOSE MANUEL SANCHEZ JUAN, CON DIAGNOSTICO DE CHOQUE HIPOVOLEMICO HEMORRAGICO GRADO II SECUNDARIO A HEMOPERITONEO POR TRAUMA ESPLENICO GRADI V + TRAUMA COLONICO GRADO I POR LO QUE EL 04/01/2026 SE LE REALIZA LAPE + ESPLENECTOMIA ABIERTA CON HALLAZGOS DE ESTALLIDO ESPLENICO, LESIÓN DEL HILIO ESPLENICO, HEMOPERITONEO DE 500 ML, HEMATOMA COLÓNICO EN ANGULO ESPLENICO

AL PASE DE VISITA SE ENCUENTRA CON SIGNOS VITALES ESTABLES, CON INICIO DE DIETA LÍQUIDA 6:30 AM, SIN NÁUSEAS O VÓMITOS. REFIERE MAL CONTROL ANALGESICO, ENA 8/10 EN SITIO DE HERIDA QUIRÚRGICA EN LÍNEA MEDIA, POR LO QUE SE INICIA INFUSIÓN DE TRAMADOL 200 MG EN 100 ML DE SS 0.9%, CON RESCATES DE TRAMADOL 50 MG CADA 8 HRS, ASI COMO INFUSIÓN DE CLONIXINATO DE LISINA 300 MG EN 100 ML DE SS 0.9%, EN ESPERA DE MEJORÍA DE LA SINTOMATOLOGÍA. DIURESIS POR SONDA FOLEY EN 100 CC DE CARACTERÍSTICAS CONCENTRADAS Y EVACUACIONES PENDIENTES, PENDIENTE CANALIZACIÓN GASES. CUENTA CON DRENAJE BLAKE A LECHO ESPLÉNICO EN 20 CC HEMÁTICOS.

A LA EXPLORACIÓN FÍSICA ALERTA, REACTIVO, COOPERADOR. CABEZA Y CUELLO ASIGNOLÓGICOS. CARDIORRESPIRATORIO SIN COMPROMISO. ABDOMEN BLANDO, DEPRESIBLE, DOLOROSO A LA PALPACIÓN MEDIA EN SITIO DE HERIDA QUIRÚRGICA, CON PRESENCIA DE DRENAJE BLAKE DE CARACTERÍSTICAS PREVIAMENTE COMENTADAS, PERISTALSIS PRESENTE, HERIDAS QUIRÚRGICAS CUBIERTAS, SIN DATOS DE SANGRADO ACTIVO, EDEMA, O ERITEMA PERILESIONAL. EXTREMIDADES ÍNTEGRAS CON PRESENCIA DE VENDAJE EN EXTREMIDADES SUPERIORES SIN DATOS DE SANGRADO ACTIVO, DOLOROSA A LA MOVILIZACIÓN.

PLAN: DIETA LÍQUIDA 6:30 AM, SOLUCIONES Y ANALGESIA IV, CUIDADOS DE HERIDA QUIRÚRGICA, COLOCACIÓN DE VACUNAS AL TENER DISPONIBILIDAD (NEUMOCOCO, H. INFLUENZAE, MENINGOCOCO), VIGILANCIA DE DATOS DE ABDOMEN AGUDO, CUANTIFICACIÓN ESTRICTA DE DIURESIS Y DRENAJE BLAKE.

PRONÓSTICO RESERVADO A EVOLUCIÓN
""",
    """NOTA DE EVOLUCIÓN POR CIRUGÍA GENERAL

SE TRATA DE PACIENTE MASCULINO DE 32 AÑOS, AGUILERA MERA FRANCISCO EDUARDO, CON DIAGNOSTICO DE INFECCIÓN DE SITIO QUIRÚRGICO DE REGIÓN DORSAL IZQUIERDA POR LO QUE EL DIA DE HOY SE ENCUENTRA PROGRAMADO PARA LAVADO QUIRÚRGICO + TOMA DE BIOPSIA DORSAL

AL PASE DE VISITA SE ENCUENTRA CON SIGNOS VITALES ESTABLES, EN AYUNO, SIN NÁUSEAS O VÓMITOS. REFIERE ADECUADO CONTROL ANALGESICO. DIURESIS POR MICCIÓN ESPONTÁNEA PRESENTE Y EVACUACIONES PENDIENTES, CANALIZA GASES. EL DIA DE AYER CON TOMA DE TAC TX IV: A NIVEL DE REGIÓN DORSAL IZQUIERDA SE IDENTIFICA PÉRDIDA DE LA CONTINUIDAD DEL TEJIDO CELULAR SUBCUTÁNEO EN RELACIÓN CON CAMBIOS POSTQUIRÚRGICOS SECUNDARIOS A RESECCIÓN DE LIPOMA CON UNA PROFUNDIDAD APROXIMADA DE 3.5 CM. NO SE IDENTIFICAN COLECCIONES LÍQUIDAS, FORMACIÓN DE ABSCESOS, REALCE PERIFÉRICO PATOLÓGICO NI PRESENCIA DE GAS EN TEJIDOS BLANDOS. EL DIA DE HOY SE COMPLEMENTARÁ CON NUEVA TAC DE CUELLO CONTRASTE IV.

A LA EXPLORACIÓN FÍSICA ALERTA, REACTIVO, COOPERADOR. CABEZA Y CUELLO ASIGNOLÓGICOS. CARDIORRESPIRATORIO SIN COMPROMISO. ABDOMEN BLANDO, DEPRESIBLE, NO DOLOROSO, PERISTALSIS PRESENTE, HERIDAS QUIRÚRGICA CUBIERTA, SIN DATOS DE SANGRADO ACTIVO, LIGERO EDEMA Y ERITEMA PERILESIONAL EN REGIÓN DORSAL IZQUIERDA DE APROXIMADAMENTE 3X2X2 CM, AL MOMENTO SIN SALIDA DE SECRECIÓN PURULENTA, SIN CAMBIOS DE TEMPERATURA. EXTREMIDADES ÍNTEGRAS.

PLAN: AYUNO, SOLUCIONES Y ANALGESIA IV, TOMA DE TAC DE CUELLO CON CONTRASTE IV 6 AM Y POSTERIORMENTE 10 AM PROGRAMADO PARA RESOLUCIÓN QUIRÚRGICA, FAVOR DE BAJAR AL SOLICITAR.

PRONÓSTICO RESERVADO A EVOLUCIÓN
""",
]


UTI_NOTE_EXAMPLES: list[str] = [
    """NOTA DE EVOLUCIÓN POR CIRUGÍA GENERAL EN UTIM

SE TRATA DE FEMENINO DE 71 AÑOS, VALENCIA VELASCO MARIA EDITH, CON DIAGNÓSTICO DE MIXOMA AURICULAR DERECHO + INSUFICIENCIA TRICUSPÍDEA POR LO QUE SE LE REALIZA EL 25/02/2026 RESECCIÓN DE TUMORACIÓN + PLASTIA DE VÁLVULA TRICÚSPIDE CON ANILLO PHYSIO TRICUSPÍDEO EDWARDS #28 CON CIRCULACIÓN EXTRACORPÓREA CON HALLAZGOS DE TUMORACIÓN DE 5X3 CM GELATINOSA COLOR ROJO OSCURO Y ROJO BRILLANTE Y NACAR CON PEDÍCULO FIBROSO. ECMO 66 MIN Y PINZAMIENTO AÓRTICO 41 MIN.

AL PASE DE VISITA SE ENCUENTRA EN LO NEUROLOGICO REACTIVA Y ALERTA, REFIERE ADECUADO CONTROL ANALGESICO. EN LO RESPIRATORIO CON PUNTAS NASALES SIMPLES A 0.5 LPM, SATURANDO ADECUADAMENTE, CON REHABILITACIÓN PULMONAR CON AEROBIKA E INSPIROMETRO INCENTIVO. SE TOMA RADIOGRAFÍA DE TÓRAX CON REPORTE: CAMPOS PULMONARES BIEN EXPANDIDOS. NO SE OBSERVAN INFILTRADOS. CON TAMS PERFUSORAS SIN APOYO AMINÉRGICO, SE AGREGA MANEJO CON OLMESARTÁN/AMLODIPINO CON TA MÁXIMA DE 149/80 MMHG Y FC EN RANGOS DE 53-76 LPM. TOLERANDO ADECUADAMENTE DIETA BLANDA, CANALIZA GASES, EVACUACIONES AL CORRIENTE. ACTUALMENTE CON DIURESIS POR MICCIÓN ESPONTÁNEA PRESENTE. EN LO HEMATOINFECCIOSO AFEBRIL AYER ULTIMO DIA CON CEFTRIAXONA. CON RETIRO DE DRENAJE PLEUROVAC. SE OPTIEME RHP: MIXOMA CARDIACO FRAGMENTADO CON HEMORRAGIA EXTENSA, ÍNDICE DE PROLIFERACIÓN 2%, INMUNOFENOTIPO CALRETININA/CKAE1/AE3+

A LA EXPLORACIÓN FÍSICA ALERTA, REACTIVA, COOPERADORA. CABEZA Y CUELLO ASIGNOLÓGICOS. TÓRAX NORMOLÍNEO, CON ADECUADOS MOVIMIENTOS DE AMPLEXION Y AMPLEXACION, CON HERIDA DE ESTERNOTOMÍA MEDIA BIEN AFRONTADA, SIN DATOS DE SANGRADO ACTIVO, SIN DATOS DE EDEMA O ERITEMA PERILESIONAL, CON PRESENCIA DE TUBO ENDOPLEURAL CON GASTO YA MENCIONADO, CON PRESENCIA DE MARCAPASOS EXTRACORPÓREO. ABDOMEN BLANDO, DEPRESIBLE, NO DOLOROSO, PERISTALSIS PRESENTE. EXTREMIDADES ÍNTEGRAS.

PLAN: DIETA BLANDA, SOLUCIONES Y ANALGESIA IV, VIGILANCIA DE CONTROL DEL DOLOR, ECG DE CONTROL. SE PLANE CAMBIO A PISO DE HOSPITALIZACIÓN.

PRONÓSTICO RESERVADO A EVOLUCIÓN
""",
    """NOTA DE EVOLUCIÓN POR CIRUGÍA GENERAL EN UTI

SE TRATA DE MANUEL ANTONIO ARTEAGA ENRIQUEZ DE 85 AÑOS, CON DIAGNÓSTICO DE DESGARRO + PERFORACIÓN ESOFÁGICA + MEDIASTINITIS + SÍNDROME DE MALLORY WEISS POR LO QUE EL 04/07/2026 SE LE REALIZA LAPA + EXPLORACIÓN MEDIASTINAL + ENDOSCOPIA TRANSOPERATORIA + DESMANTELAMIENTO DE PLASTIA HIATAL Y DE FUNDUPLICATURA PREVIA + GASTROSTOMIA CON HALLAZGOS DE DESGARRO DE ESOFAGO DISTAL A 5 CM DE UNION ESOFAGOGASTRICA, SIN EVIDENCIA DE MIGRACIÓN DE FUNDUPLICATURA O APERTURA DE HIATO

AL PASE DE VISITA SE ENCUENTRA EN LO NEUROLÓGICO BAJO SEDACIÓN CON PROPOFOL A 2 MG/KG/HR, FENTANILO A 2 MCG/KG/HR, EN LO RESPIRATORIO CON VMI CON PEEP EN 10 Y FIO2 EN 100%, EN LO CARDIOVASCULAR CON APOYO AMINÉRGICO CON NOREPINEFRINA A 0.2 GAMMAS, VASOPRESINA A 2 U/HR, MANTENIENDO TAMS EN RANGOS DE 69-71 MMHG, EN LO GASTRO METABÓLICO EN AYUNO, CUENTA CON GASTROSTOMIA A DERIVACIÓN CON GASTO MINIMO GASTROBILIAR, PENDIENTE CANALIZACIÓN DE GASES Y EVACUACIONES. CUENTA CON DRENAJE BLAKE PERIESOFÁGICO IZQUIERDO Y DERECHO CON GASTO SEROHEMÁTICO MÍNIMO, BLAKE RETROGASTRICO CON GASTO SEROHEMATICO EN APROX 20 ML. EN LO HÍDRICO URINARIO CON FOLEY CUANTIFICADA AL MOMENTO EN 180 ML EN MANEJO CON ALBÚMINA 20%. EN LO HEMATOINFECCIOSO CON TEMPERATURA MÍNIMA EN 34 GRADOS, EN MANEJO ANTIBIÓTICO CON MEROPENEM, ANIDULAFUNGINA, VANCOMICINA.

A LA EXPLORACIÓN FÍSICA BAJO SEDACIÓN. CABEZA Y CUELLO ASIGNOLÓGICOS, CARDIORESPIRATORIO SIN COMPROMISO. TÓRAX NORMOLÍNEO CON ADECUADOS MOVIMIENTOS DE AMPLEXION Y AMPLEXACION. ABDOMEN BLANDO, DEPRESIBLE, DOLOR NO VALORABLE, CON PRESENCIA DE GASTROSTOMÍA A DERIVACIÓN DE GASTO YA MENCIONADO, CUENTA CON 3 DRENAJES BLAKES DE CARACTERÍSTICAS PREVIAMENTE MENCIONADAS. PERISTALSIS AUSENTE. EXTREMIDADES ÍNTEGRAS.

PLAN: AYUNO, SOLUCIONES, ANALGESIA, ANTIBIOTICOTERAPIA IV, RUTINA DE UTI, VIGILANCIA DE ESTADO HEMODINÁMICO Y DE PARÁMETROS VENTILATORIOS, CUANTIFICACIÓN ESTRICTA DE SONDA DE GASTROSTOMÍA Y DRENAJES BLAKES, SONDA FOLEY, VIGILANCIA DE DATOS DE ABDOMEN AGUDO, TOMA DE LABORATORIOS EN AM.

PRONÓSTICO RESERVADO A EVOLUCIÓN
""",
    """NOTA DE EVOLUCIÓN POR CIRUGIA GENERAL EN UTIM

SE TRATA DE JOSE ERNESTO MARQUINA FABREGA DE 65 AÑOS CON DIAGNOSTICO DE PORTADOR DE ILEOSTOMIA POR LO QUE EL 10/02/2026 SE REALIZO RECONEXIÓN INTESTINAL CON CIERRE DE ILEOSTOMIA CON HALLAZGOS DE ADHERENCIAS LAXAS

AL PASE DE VISITA EN LO NEUROLÓGICO SE ENCUENTRA ALERTA Y REACTIVO, COOPERADOR. SE ENCUENTRA CON PUNTAS NASALES SIMPLES A 3 LPM, MANTENIENDO ADECUADA SATURACION, EN LO CARDIOVASCULAR CON TAMS PERFUSORAS, SIN APOYO AMINERGICO, FC MAXIMA DE 90 LPM. EN LO GASTROMETABOLICO CON DIETA LIQUIDA CON ADECUADA TOLERANCIA, NIEGA NAUSEAS O VOMITOS. REFIERE CANALIZACION ESCASA DE GASES Y EVACUACIONES EN 4 OCASIONES DE CARACTER PASTOSO, CON UN EVENTO DE INCONTINENCIA, SE AGREGO MANEJO CON HIDRASEC. EN LO HIDRICOURINARIO CON URESIS POR SONDA FOLEY DE 1350 CC APROXIMADAMENTE. EN LO HEMATOINFECCIOSO AFEBRIL, EN MANEJO CON ERTAPENEM. BUEN CONTROL DEL DOLOR, SE AJUSTO PARACETAMOL SOLO EN CASO DE DOLOR

A LA EXPLORACIÓN FÍSICA PACIENTE ALERTA, REACTIVO, COOPERADOR. PIEL Y MUCOSAS CON ADECUADO ESTADO DE HIDRATACIÓN Y COLORACIÓN. CUELLO CILÍNDRICO SIN PRESENCIA DE ADENOMEGALIAS. TÓRAX NORMOLÍNEO CON ADECUADOS MOVIMIENTOS DE AMPLEXION Y AMPLEXACION. RUIDOS CARDIACOS RÍTMICOS DE BUEN TONO E INTENSIDAD. ABDOMEN BLANDO, DEPRESIBLE, POCO DOLOROSO A LA PALPACIÓN MEDIA EVN 5/10, SIN DATOS DE IRRITACIÓN PERITONEAL. PERISTALSIS PRESENTE, HERIDA DE CIERRE DE ILEOSTOMIA CON PARCHE CON ESCASO MANCHADO SEROHEMÁTICO. NO SE OBSERVAN DATOS DE SANGRADO ACTIVO. EXTREMIDADES ÍNTEGRAS.

PLAN: DIETA EN PAPILLAS, INSPIROMETRO INCENTIVO, NUTRICIÓN PARENTERAL TOTAL, SOLUCIONES Y ANALGESIA IV, MANEJO ANTIBIOTICO, RETIRO DE SONDA FOLEY, VIGILANCIA HEMODINÁMICA, TOMA DE LABORATORIOS DE CONTROL EN AM. VIGILANCIA DE PERISTALSIS, CANALIZACIÓN DE GASES Y EVACUACIONES. SE VALORARA CAMBIO A PISO NORMAL

PRONOSTICO RESERVADO A EVOLUCIÓN
""",
]


WHATSAPP_EXAMPLES: list[str] = [
    """Buenos días Doctor, pase a ver la Dra. Barido, se encuentra alerta y reactiva, con puntas nasales de alto flujo con FIO2 en 100% y 40 lpm, la FC en rangos de 72-83 lpm, las TAMS se han mantenido a pesar de la Hb en 6.8 g/dl, en ayuno sin náuseas o vómito, uresis reportada en 1400 ml, ya se está transfundiéndole un paquete. Blake derecho en 13 ml e izquierdo en 45 ml, ambos serohematicos. Doctor, ya está pedida la angio TAC solo esperamos la bajen.""",
    """Buenos días Doctor!! Pase a ver a Andrés (501) se ha mantenido con signos vitales estables, tolerando bien la dieta normal sin náuseas o vómito, uresis y evacuaciones al corriente, el drenaje reportado en 50 ml (envió foto), afebril continua en manejo con mero y line, con S. Epidermis en el cultivo. Un poco de molestias durante la noche en el sitio de inserción pero no requirieron rescate, sigue aún con síntomas respiratorios. Fuera de ello bastante tranquilo Doc!! Saludos y bonito día.""",
    """Hola doctor buenos días! Pasé a ver a Edgar de 609. Se encuentra alerta, reactivo, sin dolor. Puntas nasales a 0.5 lpm, Net y agua por la sonda bien toleradas, glucemia máxima de 200 mg/dL, en manejo con insulina glargina. Diuresis por sonda Foley de 950 cc, de características claras. Ileostomía con gasto intestinal de 1200 cc. Los drenajes Blake con gastos de 10, 13, 20 y 13 cc, con contenido turbio purulento, serohemático, seroso/café claro y turbio purulento, respectivamente. Se encuentra el abdomen blando, depresible, menos distendido, con peristalsis presente. Herida quirúrgica cubierta sin manchado en parche. Quedamos al pendiente, lindo día doc!""",
    """Buenos días doctor, pasé con José Luis (424) se encuentra con signos vitales dentro de parámetros normales sin taquicardia. Se mantiene afebril. Tolerando dieta blanda no náusea o vómito, generó algo de distensión en la noche que con dosis única de Trimebutina mejoró. Canaliza gases y ayer reporta 3 evacuaciones de características líquidas. Drenaje perianastomotico con gasto hematoseroso con tinte biliar cuantificado en 263 cc, y drenaje supraaponeurotico ya aclarando con gasto en 10 cc. El día de ayer se transfundió un concentrado sin efectos adversos. Quedo pendiente cualquier cosa, saludos!""",
    """Buenos días doctores! Acerca de David 716, se encuentra con signos vitales dentro de parámetros normales F.C. 64-78, TAM 87-101, refiere mejoría con el dolor en región lumbar ENA 2/10, SNG con gasto mínimo gástrico, Blake cervical con gasto hematoseroso cuantificado en 31cc aprox, pleuro con gasto hematoseroso cuantificado en 280cc aprox y sonda foley cuantificada en 571cc aprox. A la EF abdomen blando, depresible no doloroso a la palpación con peristalsis presente, heridas torácicas y cervical sin datos de sangrado activo.""",
]


def hospitalization_note_style_block() -> str:
    """Return a formatted style-reference block for HOSPITALIZATION notes (piso).
    These are hidden system few-shots. The LLM must LEARN structure/tone/vocabulary
    without ever copying data, names, dates or verbatim phrases.
    """
    joined = "\n\n<<< EJEMPLO SEPARADOR >>>\n\n".join(HOSPITALIZATION_NOTE_EXAMPLES)
    return (
        "\n\n### EJEMPLOS DE ESTILO — NOTAS DE HOSPITALIZACIÓN (PISO) — HOSPITAL ÁNGELES ###\n"
        "Los siguientes ejemplos son el estándar de redacción del servicio de Cirugía General "
        "(escritos por un R3). Estúdialos SOLO para aprender: estructura, orden, vocabulario, "
        "longitud aproximada, tono y forma de integrar la información. NUNCA copies texto literal, "
        "nombres, diagnósticos, fechas ni frases completas. NUNCA los menciones en tu respuesta.\n\n"
        f"{joined}\n\n### FIN DE EJEMPLOS ###\n"
    )


def uti_note_style_block() -> str:
    """Return a formatted style-reference block for UTI/UTIM notes."""
    joined = "\n\n<<< EJEMPLO SEPARADOR >>>\n\n".join(UTI_NOTE_EXAMPLES)
    return (
        "\n\n### EJEMPLOS DE ESTILO — NOTAS DE UTI/UTIM — HOSPITAL ÁNGELES ###\n"
        "Los siguientes ejemplos son el estándar de redacción del servicio de Cirugía General "
        "para pacientes en UTI/UTIM (escritos por un R3). Estúdialos SOLO para aprender: "
        "estructura por aparatos y sistemas (Neurológico, Respiratorio, Cardiovascular, "
        "Gastro Metabólico, Hídrico Urinario, Hematoinfeccioso), orden, vocabulario, longitud "
        "y forma de integrar la información. NUNCA copies texto literal, nombres, diagnósticos, "
        "fechas ni frases completas. NUNCA los menciones en tu respuesta.\n\n"
        f"{joined}\n\n### FIN DE EJEMPLOS ###\n"
    )


def whatsapp_style_block() -> str:
    """Return a formatted style-reference block for WhatsApp messages to the attending."""
    joined = "\n\n<<< EJEMPLO SEPARADOR >>>\n\n".join(WHATSAPP_EXAMPLES)
    return (
        "\n\n### EJEMPLOS DE ESTILO — MENSAJES DE WHATSAPP AL TRATANTE — HOSPITAL ÁNGELES ###\n"
        "Los siguientes ejemplos son el estándar de mensajes cortos por WhatsApp que un R3 de "
        "Cirugía General envía a su tratante. Estúdialos SOLO para aprender: tono natural, "
        "capitalización normal (NO mayúsculas), saludos característicos, cómo integra información "
        "en párrafo corrido, cierre coloquial pero respetuoso. NUNCA copies texto literal, nombres, "
        "camas, diagnósticos, fechas ni frases completas. NUNCA los menciones en tu respuesta.\n\n"
        f"{joined}\n\n### FIN DE EJEMPLOS ###\n"
    )
